# ex4: ex4.o
# 	gcc -Wall ex4.o -lpthread -o ex4
# ex4.o: ex4.c
# 	gcc -Wall -c -D_REENTRANT ex4.c

# ex5: ex5.o
# 	gcc -Wall ex5.o -lpthread -o ex5
# ex5.o: ex5.c
# 	gcc -Wall -c -D_REENTRANT ex5.c

ex6: ex6.o
	gcc -Wall ex6.o -lpthread -o ex6
ex6.o: ex6.c
	gcc -Wall -c -D_REENTRANT ex6.c

# teste: teste.o
# 	gcc -Wall teste.o -lpthread -o teste
# teste.o: teste.c
# 	gcc -Wall -c -D_REENTRANT teste.c
